# server config
server:
  address: 0.0.0.0
  port: ${PORT:8443} # keep sync in Dockerfile API_PORT
  compression:
    enabled: true
  http:
    port: ${UNSECURE_PORT:8081} # keep sync in Dockerfile UNSECURE_API_PORT
  ssl:
    enabled: ${ENABLE_SSL:true}
    key-store-type: PKCS12
    key-store: ${KEY_STORE:file:./mTLS/server-key-store.p12}
    key-store-password: ${KEY_STORE_PASSWORD:keyStoreSecret}
    client-auth: ${ENABLE_MTLS:need} # none / want / need
    trust-store: ${TRUST_STORE:file:./mTLS/server-trust-store.p12}
    trust-store-password: ${TRUST_STORE_PASSWORD:trustStoreSecret}
# Swagger UI config
springdoc:
  api-docs:
    path: /api-docs
  packagesToScan: "uk.org.ca.stub.simulator.rest.controller"
  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter: method

cas:
  signature: "SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"

spring:
  application:
    name: "C&A Stub"
  h2:
    console:
      enabled: true
      path: /data
      settings:
        web-allow-others: true
        trace: false
  datasource:
    url: ${DB:jdbc:h2:file:./db/cas}
    username: ${DB_USER:sa}
    password: ${DB_PASS:}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true

logging.level.root: OFF
